
FROM hahlabs/angular:dev
LABEL version.edudate-view="alpha-0.02.01"

USER root
COPY files/. files
# Update, Upgrade, install packages
RUN apt -y update && apt -y upgrade
# Setup workspace
RUN files/setup-nginx-virtual-host.sh
RUN files/setup-edudate-user.sh 
USER edudate
WORKDIR /app/edudate-view

# Enable port for edudate-view
EXPOSE 8102