FROM ubuntu:latest
LABEL version.angular="14-lts" \
      version.ubuntu="22.04-lts" \
      version.firebase="9.1.0" \
      version.nvm="8" \
      version.npm="16" \
      version.hahlabs-angular="alpha-00.02.02" \
      version.description="Timezone setup"

USER root
RUN apt update \
 && apt -y upgrade \
 && apt install -y nginx curl npm sudo vim

ENV TZ="America/Vancouver"
RUN DEBIAN_FRONTEND=noninteractive TZ=America/Vancouver apt-get -y install tzdata && ln -fs /usr/share/zoneinfo/America/Vancouver /etc/localtime

WORKDIR /home/hahlabs
COPY files/. files/
RUN files/setup-hahlabs-user.sh \
   && files/setup-nginx-virtual-host.sh

USER hahlabs

RUN files/install-nvm.sh


RUN files/install-angular.sh
     
RUN files/install-firebase.sh
ENTRYPOINT sudo service nginx start && bash

EXPOSE 8101 4200 9005